Game_Interpreter:1411:in `eval': There is no entry under the name of 'Xaver'., NameError
	from (eval):1:in `command_355'
	from Game_Interpreter:1411:in `eval'
	from Game_Interpreter:1411:in `command_355'
	from Game_Interpreter:197:in `execute_command'
	from Game_Interpreter:103:in `run'
	from Game_Interpreter:60:in `block in create_fiber'